// 인증 관련
export enum AuthErrorCode {
  AUTH_URL_GENERATION_FAILED = "OAUTH_URL_GENERATION_FAILED",

  // OAuth/Google 인증 관련
  AUTH_EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED", // "이메일이 인증되지 않은 Google 계정입니다."
  AUTH_TOKEN_EXCHANGE_FAILED = "AUTH_TOKEN_EXCHANGE_FAILED", // "Google 토큰 교환에 실패했습니다."
  AUTH_USER_INFO_FAILED = "AUTH_USER_INFO_FAILED", // "Google 사용자 정보를 가져올 수 없습니다."
  AUTH_OAUTH_PROCESSING_ERROR = "AUTH_OAUTH_PROCESSING_ERROR", // "OAuth 처리 중 알 수 없는 오류가 발생했습니다."

  // JWT/리프레시 토큰 관련
  AUTH_INVALID_ACCESS_TOKEN = "AUTH_INVALID_ACCESS_TOKEN",
  AUTH_INVALID_REFRESH_TOKEN = "AUTH_INVALID_REFRESH_TOKEN", // "유효하지 않은 리프레시 토큰입니다."
  AUTH_ACCESS_TOKEN_EXPIRED = "AUTH_ACCESS_TOKEN_EXPIRED",
  AUTH_REFRESH_TOKEN_EXPIRED = "AUTH_REFRESH_TOKEN_EXPIRED", // "리프레시 토큰이 만료되었습니다."
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND", // "사용자를 찾을 수 없습니다."
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",

  // 추가 필요한 코드들
  AUTH_INVALID_STATE = "AUTH_INVALID_STATE", // OAuth state 검증 실패
  AUTH_PROVIDER_ERROR = "AUTH_PROVIDER_ERROR", // 소셜 로그인 제공자 오류
}

// 사용자 관련
export enum UserErrorCode {
  USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND", // "사용자가 없습니다"
  USER_NO_UPDATE_CONTENT = "USER_NO_UPDATE_CONTENT", // "수정할 내용이 없습니다"
  USER_NICKNAME_SAME_AS_CURRENT = "USER_NICKNAME_SAME_AS_CURRENT", // "현재 닉네임과 동일합니다"
  USER_NICKNAME_ALREADY_EXISTS = "USER_NICKNAME_ALREADY_EXISTS", // "이미 사용 중인 닉네임입니다"
}

// 일정 관련
export enum ScheduleErrorCode {
  SCHEDULE_USER_NOT_FOUND = "SCHEDULE_USER_NOT_FOUND", // "사용자를 찾을 수 없습니다."
  SCHEDULE_STREAMER_NOT_FOUND = "SCHEDULE_STREAMER_NOT_FOUND", // "스트리머를 찾을 수 없습니다."
  SCHEDULE_STREAMER_NOT_VERIFIED = "SCHEDULE_STREAMER_NOT_VERIFIED", // "검증이 완료된 스트리머가 아닙니다."
  SCHEDULE_PAST_DATE_NOT_ALLOWED = "SCHEDULE_PAST_DATE_NOT_ALLOWED", // "과거 날짜에는 일정을 생성할 수 없습니다."
  SCHEDULE_DATE_TIME_MISMATCH = "SCHEDULE_DATE_TIME_MISMATCH", // "방송일과 방송시간의 일자가 다릅니다."
  SCHEDULE_ALREADY_EXISTS = "SCHEDULE_ALREADY_EXISTS", // "해당 날짜에 이미 일정이 존재합니다."
  SCHEDULE_SAVE_FAILED = "SCHEDULE_SAVE_FAILED", // "일정 저장 후 조회에 실패했습니다."
  SCHEDULE_NOT_FOUND = "SCHEDULE_NOT_FOUND", // "일정을 찾을 수 없습니다."
  SCHEDULE_CONFLICT_MODIFIED = "SCHEDULE_CONFLICT_MODIFIED", // "다른 사용자가 이미 수정한 일정입니다."
  SCHEDULE_TIME_ONLY_FOR_SCHEDULED = "SCHEDULE_TIME_ONLY_FOR_SCHEDULED", // "확정된 일정(SCHEDULED)에서만 시작 시간을 설정할 수 있습니다."
  SCHEDULE_SCHEDULED_NEEDS_TIME = "SCHEDULE_SCHEDULED_NEEDS_TIME", // "확정된 일정(SCHEDULED)에는 시작 시간이 필요합니다."
  SCHEDULE_UPDATE_FAILED = "SCHEDULE_UPDATE_FAILED", // "일정 업데이트 후 조회에 실패했습니다."
  SCHEDULE_DELETE_ADMIN_ONLY = "SCHEDULE_DELETE_ADMIN_ONLY",
}

// 스트리머 관련
export enum StreamerErrorCode {
  STREAMER_USER_NOT_FOUND = "STREAMER_USER_NOT_FOUND", // "사용자를 찾을 수 없습니다."
  STREAMER_ALREADY_EXISTS = "STREAMER_ALREADY_EXISTS", // "방송인이 플랫폼에 이미 존재합니다."
  STREAMER_NOT_FOUND = "STREAMER_NOT_FOUND", // "방송인을 찾을 수 없습니다."
  STREAMER_SEARCH_TERM_TOO_SHORT = "STREAMER_SEARCH_TERM_TOO_SHORT", // "검색어는 최소 2글자 이상이어야 합니다."
  STREAMER_CONFLICT_MODIFIED = "STREAMER_CONFLICT_MODIFIED", // "방송인 정보가 다른 사용자에 의해 수정되었습니다."
  STREAMER_NAME_ALREADY_EXISTS = "STREAMER_NAME_ALREADY_EXISTS", // "방송인 이름이 이미 존재합니다."
  STREAMER_DELETE_ADMIN_ONLY = "STREAMER_DELETE_ADMIN_ONLY",
}

export type ApiErrorCode = AuthErrorCode | UserErrorCode | ScheduleErrorCode | StreamerErrorCode;
